'use strict';
(() => {
const A=window.Aura,$=A.$,icon=A.icon;
let gamePage='library',gameCleanups=[];
const stopGame=()=>{gameCleanups.splice(0).forEach(fn=>fn());};
const listenKey=fn=>{document.addEventListener('keydown',fn);gameCleanups.push(()=>document.removeEventListener('keydown',fn));};
function swipe(el,callback){let start=null;el.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};el.setPointerCapture(e.pointerId);});el.addEventListener('pointerup',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.max(Math.abs(dx),Math.abs(dy))<17)return;callback(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});el.addEventListener('pointercancel',()=>start=null);}
function library(){stopGame();gamePage='library';A.statusTheme(false);A.view(A.nav('ゲーム')+`<div class="app-content"><h1 class="app-title">ちょっと、夢中に。</h1><p class="app-subtitle">ひと休みのつもりが、もう一回。</p><div class="games-hero"><small>SMALL GAMES. BIG LITTLE JOYS.</small><h2>遊び心を、<br>ポケットに。</h2><p>シンプルだから、奥が深い。</p><span class="hero-block">2048</span></div><p class="section-label">YOUR LITTLE ARCADE</p><button class="game-card" data-action="gameOpen" data-game="2048"><span class="game-cover g2048">2048</span><div><strong>2048</strong><p>重ねて、つなげて、その先へ。</p><small>PUZZLE · BEST ${A.load('2048best',0).toLocaleString()}</small></div><span>›</span></button><button class="game-card" data-action="gameOpen" data-game="snake"><span class="game-cover gsnake">⌁</span><div><strong>Little Snake</strong><p>懐かしくて、新しい。</p><small>ARCADE · BEST ${A.load('snakeBest',0)}</small></div><span>›</span></button><button class="game-card" data-action="gameOpen" data-game="memory"><span class="game-cover gmemory">✿</span><div><strong>Memory Garden</strong><p>同じかたちを、見つけよう。</p><small>MEMORY · ${A.load('memoryBest',0)?'BEST '+A.load('memoryBest',0)+' MOVES':'TAKE YOUR TIME'}</small></div><span>›</span></button><p class="notes-footer">ハイスコアは、このブラウザに保存されます。</p></div>`);}
A.apps.games.render=arg=>{A.cleanups.push(stopGame);if(['2048','snake','memory'].includes(arg))openGame(arg);else library();};
A.actions.gamesLibrary=library;A.actions.gameOpen=el=>openGame(el.dataset.game);
function openGame(id){stopGame();gamePage=id;A.statusTheme(false);if(id==='2048')game2048();if(id==='snake')gameSnake();if(id==='memory')gameMemory();}
// 2048 — canonical single-merge-per-move rules, local progress, undo.
const saved2048=A.load('2048state',null);
let tiles=saved2048?.tiles?.length===16?saved2048.tiles:Array(16).fill(0),score=saved2048?.score||0,best=A.load('2048best',0),undo=null,won=false;
function spawn(){const empty=tiles.map((v,i)=>v===0?i:-1).filter(i=>i>=0);if(empty.length)tiles[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4;}
if(!tiles.some(Boolean)){spawn();spawn();}
function save2048(){best=Math.max(best,score);A.save('2048best',best);A.save('2048state',{tiles,score});}
function mergeLine(line){const nonzero=line.filter(Boolean),out=[];let gain=0;for(let i=0;i<nonzero.length;i++){if(nonzero[i]===nonzero[i+1]){const value=nonzero[i]*2;out.push(value);gain+=value;i++;}else out.push(nonzero[i]);}while(out.length<4)out.push(0);return {line:out,gain};}
function movable(){if(tiles.includes(0))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const i=r*4+c;if(c<3&&tiles[i]===tiles[i+1])return true;if(r<3&&tiles[i]===tiles[i+4])return true;}return false;}
function move2048(direction){if(gamePage!=='2048'||!$('#overlay').hidden)return;const before=[...tiles],beforeScore=score;let gain=0;for(let row=0;row<4;row++){const indices=Array.from({length:4},(_,col)=>direction==='left'?row*4+col:direction==='right'?row*4+(3-col):direction==='up'?col*4+row:(3-col)*4+row);const result=mergeLine(indices.map(i=>tiles[i]));indices.forEach((i,k)=>tiles[i]=result.line[k]);gain+=result.gain;}if(before.every((v,i)=>v===tiles[i]))return;undo={tiles:before,score:beforeScore};score+=gain;spawn();save2048();render2048();A.haptic();if(!won&&tiles.includes(2048)){won=true;A.toast('2048達成！その先にも挑戦できます。');}}
function game2048(){A.view(A.nav('2048',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2>2048<span style="font-size:13px;margin-left:5px;letter-spacing:0">.</span></h2><div class="game-scores"><div class="score-badge"><small>SCORE</small><strong id="score-2048">${score}</strong></div><div class="score-badge" style="background:#b7a58e"><small>BEST</small><strong id="best-2048">${best}</strong></div></div></div><p class="game-instructions">同じ数字を重ねて、<strong>2048</strong>を目指そう。<br>盤面をスワイプ、または矢印キーで移動。</p><div class="board-2048" id="board-2048" aria-label="2048の盤面" tabindex="0"></div><div class="game-toolbar"><button data-action="undo2048">↶ 一手戻す</button><button data-action="restart2048">↻ もう一度</button></div><div class="game-status" id="status-2048" role="status"></div><div class="direction-pad" style="margin-top:10px">${[['up','↑'],['left','←'],['down','↓'],['right','→']].map(([d,s])=>`<button data-action="move2048" data-value="${d}" aria-label="${d}" style="color:#9c8b75;background:#e9e2d8;border-color:#ded4c6">${s}</button>`).join('')}</div><p class="notes-footer">Take a breath. Make your next move.</p></div>`);render2048();swipe($('#board-2048'),move2048);listenKey(e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(d&&$('#overlay').hidden){e.preventDefault();move2048(d);}});}
function render2048(){if(!$('#board-2048'))return;$('#board-2048').innerHTML=tiles.map(v=>`<span class="tile-2048" data-value="${v}" data-large="${v>=128}">${v||''}</span>`).join('');$('#score-2048').textContent=score;$('#best-2048').textContent=best;$('#status-2048').textContent=!movable()?'ゲームオーバー。「一手戻す」で考え直してみよう。':tiles.some(v=>v>=2048)?'2048達成！さらに大きな数字へ。':'';}
A.actions.move2048=el=>move2048(el.dataset.value);A.actions.undo2048=()=>{if(!undo)return A.toast('戻せる手がありません');tiles=[...undo.tiles];score=undo.score;undo=null;save2048();render2048();};A.actions.restart2048=()=>A.confirm('新しい2048をはじめる','現在の盤面をリセットします。ハイスコアは残ります。',()=>{tiles=Array(16).fill(0);score=0;undo=null;won=false;spawn();spawn();save2048();render2048();});
// Snake — grid simulation, deterministic steering, pausing on app leave.
let snake=[],snakeDirection={x:1,y:0},snakeNext={x:1,y:0},snakeFood={x:12,y:8},snakeScore=0,snakeBest=A.load('snakeBest',0),snakeRunning=false,snakeOver=false,snakeInterval=null;
const snakeSize=18;
function resetSnake(){snake=[{x:7,y:9},{x:6,y:9},{x:5,y:9},{x:4,y:9}];snakeDirection={x:1,y:0};snakeNext={x:1,y:0};snakeScore=0;snakeRunning=false;snakeOver=false;spawnFood();}
function spawnFood(){const empty=[];for(let y=0;y<snakeSize;y++)for(let x=0;x<snakeSize;x++)if(!snake.some(s=>s.x===x&&s.y===y))empty.push({x,y});if(!empty.length){snakeRunning=false;snakeOver=true;clearInterval(snakeInterval);return;}snakeFood=empty[Math.floor(Math.random()*empty.length)];}
function stopSnake(){clearInterval(snakeInterval);snakeInterval=null;snakeRunning=false;}
function gameSnake(){if(!snake.length)resetSnake();gameCleanups.push(stopSnake);A.view(A.nav('Little Snake',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2 style="font-size:29px;color:#7f9675">Little Snake<span style="font-size:15px">.</span></h2><div class="score-badge" style="background:#9caa90"><small>BEST</small><strong id="snake-best">${snakeBest}</strong></div></div><p class="game-instructions" style="color:#8b9a83">小さな実を食べて、長くなろう。<br>壁と自分のしっぽには、気をつけて。</p><div class="memory-meta" style="margin:17px 0 12px;color:#839578"><span>SCORE <strong id="snake-score">${snakeScore}</strong></span><span>18 × 18 GARDEN</span></div><canvas class="snake-board" id="snake-board" width="648" height="648" aria-label="スネークゲームの盤面"></canvas><div class="game-toolbar"><button data-action="snakeToggle" id="snake-toggle" style="background:#94a889;min-width:95px">${snakeOver?'もう一度':'▶ スタート'}</button><button data-action="snakeRestart" style="background:#dce3d7;color:#809373">↻ リセット</button></div><div class="game-status" id="snake-status" style="color:#829276">${snakeOver?'ゲームオーバー。もう一度、どうぞ。':'矢印キー・スワイプ・下のボタンで操作'}</div><div class="direction-pad">${[['up','↑'],['left','←'],['down','↓'],['right','→']].map(([d,s])=>`<button data-action="snakeDirection" data-value="${d}" aria-label="${d}">${s}</button>`).join('')}</div></div>`);drawSnake();swipe($('#snake-board'),steerSnake);listenKey(e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(!$('#overlay').hidden)return;if(d){e.preventDefault();steerSnake(d);}if(e.code==='Space'){e.preventDefault();toggleSnake();}});}
function steerSnake(d){const direction={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[d];if(!direction)return;if(direction.x===-snakeDirection.x&&direction.y===-snakeDirection.y)return;snakeNext=direction;if(!snakeRunning&&!snakeOver)toggleSnake();}
function toggleSnake(){if(snakeOver){resetSnake();}if(snakeRunning)stopSnake();else{snakeRunning=true;clearInterval(snakeInterval);snakeInterval=setInterval(tickSnake,145);}updateSnakeUi();}
function updateSnakeUi(){if(!$('#snake-toggle'))return;$('#snake-toggle').textContent=snakeOver?'もう一度':snakeRunning?'Ⅱ 一時停止':'▶ スタート';$('#snake-score').textContent=snakeScore;$('#snake-best').textContent=snakeBest;$('#snake-status').textContent=snakeOver?'ゲームオーバー。もう一度、どうぞ。':snakeRunning?'小さな実を、追いかけて。':'矢印キー・スワイプ・下のボタンで操作';drawSnake();}
function tickSnake(){if(!snakeRunning)return;if(!$('#overlay').hidden||document.hidden)return;snakeDirection={...snakeNext};const head={x:snake[0].x+snakeDirection.x,y:snake[0].y+snakeDirection.y};const eating=head.x===snakeFood.x&&head.y===snakeFood.y;const body=eating?snake:snake.slice(0,-1);if(head.x<0||head.y<0||head.x>=snakeSize||head.y>=snakeSize||body.some(s=>s.x===head.x&&s.y===head.y)){snakeOver=true;stopSnake();updateSnakeUi();return;}snake.unshift(head);if(eating){snakeScore+=10;snakeBest=Math.max(snakeBest,snakeScore);A.save('snakeBest',snakeBest);spawnFood();A.haptic();}else snake.pop();updateSnakeUi();}
function drawSnake(){const c=$('#snake-board');if(!c)return;const ctx=c.getContext('2d'),cell=c.width/snakeSize;ctx.fillStyle='#e5ecdf';ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<snakeSize;y++)for(let x=0;x<snakeSize;x++){if((x+y)%2===0){ctx.fillStyle='#dfe7d8';ctx.fillRect(x*cell,y*cell,cell,cell);}}ctx.fillStyle='#d39a7c';ctx.beginPath();ctx.arc((snakeFood.x+.5)*cell,(snakeFood.y+.5)*cell,cell*.28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#94a678';ctx.beginPath();ctx.ellipse((snakeFood.x+.57)*cell,(snakeFood.y+.19)*cell,cell*.13,cell*.06,-.6,0,Math.PI*2);ctx.fill();snake.forEach((s,i)=>{ctx.fillStyle=i===0?'#68845b':`hsl(96 19% ${49+Math.min(12,i*.65)}%)`;ctx.beginPath();ctx.roundRect(s.x*cell+2,s.y*cell+2,cell-4,cell-4,i===0?10:6);ctx.fill();});const head=snake[0];ctx.fillStyle='#f3f6eb';const dx=snakeDirection.x,dy=snakeDirection.y;const eyePositions=dx?[{x:dx>0?.69:.31,y:.3},{x:dx>0?.69:.31,y:.7}]:[{x:.3,y:dy>0?.69:.31},{x:.7,y:dy>0?.69:.31}];eyePositions.forEach(p=>{ctx.beginPath();ctx.arc((head.x+p.x)*cell,(head.y+p.y)*cell,cell*.09,0,Math.PI*2);ctx.fill();});if(!snakeRunning){ctx.fillStyle='#e5ecdf99';ctx.fillRect(0,0,c.width,c.height);ctx.textAlign='center';ctx.font='500 30px sans-serif';ctx.fillStyle='#6c815f';ctx.fillText(snakeOver?'A LITTLE BREAK.':'READY WHEN YOU ARE.',c.width/2,c.height/2);}}
A.actions.snakeToggle=toggleSnake;A.actions.snakeDirection=el=>steerSnake(el.dataset.value);A.actions.snakeRestart=()=>{stopSnake();resetSnake();updateSnakeUi();};
// Memory Garden — shuffled pairs with a race-safe reveal timer.
const symbols=['✿','☀','☾','♧','♡','✦','☁','♫'];const colors=['#cd8d9a','#d2ae69','#a394c4','#91aa81','#d1a092','#a3b3c7','#8bb3c6','#b79ac1'];
let cards=[],flipped=[],matched=[],memoryMoves=0,memoryBusy=false,memoryTimeout=null,memoryBest=A.load('memoryBest',0),memoryStart=0,memorySeconds=0,memoryClock=null;
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]];}return list;}
function resetMemory(){clearTimeout(memoryTimeout);cards=shuffle([...symbols,...symbols]);flipped=[];matched=[];memoryMoves=0;memoryBusy=false;memoryStart=0;memorySeconds=0;}
function gameMemory(){resetMemory();gameCleanups.push(()=>{clearTimeout(memoryTimeout);clearInterval(memoryClock);memoryBusy=false;});A.view(A.nav('Memory Garden',`<button data-action="gameHelp" aria-label="遊び方">?</button>`,'gamesLibrary','ゲーム')+`<div class="app-content"><div class="game-heading"><h2 style="font-size:28px;color:#9a88ac">Memory Garden<span style="font-size:15px">.</span></h2></div><p class="game-instructions" style="color:#a293ac">花、月、小さな星。<br>同じかたちを見つけて、庭を完成させよう。</p><div class="memory-meta" style="margin-top:25px"><span>MOVES <strong id="memory-moves">0</strong></span><span id="memory-time">00:00</span><span><strong id="memory-pairs">0</strong> / 8 PAIRS</span></div><div class="memory-board" id="memory-board"></div><div class="game-status" id="memory-status" style="color:#a08baa">あせらず、ひとつずつ。</div><div class="game-toolbar"><button data-action="memoryRestart" style="background:#ad9abd">↻ 新しいお庭</button><span style="font-size:10px;color:#ad9abd;align-self:center" id="memory-best">BEST ${memoryBest?memoryBest+' MOVES':'—'}</span></div><p class="notes-footer">Good things come in pairs.</p></div>`);renderMemory();memoryClock=setInterval(()=>{if(memoryStart&&matched.length<16){memorySeconds=Math.floor((Date.now()-memoryStart)/1000);if($('#memory-time'))$('#memory-time').textContent=`${String(Math.floor(memorySeconds/60)).padStart(2,'0')}:${String(memorySeconds%60).padStart(2,'0')}`;}},1000);}
function renderMemory(){if(!$('#memory-board'))return;$('#memory-board').innerHTML=cards.map((s,i)=>{const visible=flipped.includes(i)||matched.includes(i);return `<button class="memory-card ${visible?'flipped':''} ${matched.includes(i)?'matched':''}" data-action="memoryFlip" data-index="${i}" aria-label="${matched.includes(i)?'一致したカード':visible?s:'裏向きのカード '+(i+1)}" ${matched.includes(i)?'disabled':''}><span style="${visible?'color:'+colors[symbols.indexOf(s)]:''}">${visible?s:'✧'}</span></button>`;}).join('');$('#memory-moves').textContent=memoryMoves;$('#memory-pairs').textContent=matched.length/2;}
function flipCard(index){if(memoryBusy||flipped.includes(index)||matched.includes(index))return;if(!memoryStart)memoryStart=Date.now();flipped.push(index);A.haptic();renderMemory();if(flipped.length===2){memoryMoves++;const [a,b]=flipped;if(cards[a]===cards[b]){matched.push(a,b);flipped=[];renderMemory();if(matched.length===16){const elapsed=Math.floor((Date.now()-memoryStart)/1000);memoryBest=memoryBest?Math.min(memoryBest,memoryMoves):memoryMoves;A.save('memoryBest',memoryBest);$('#memory-status').textContent=`お庭が完成！ ${memoryMoves}手・${elapsed}秒でクリア。`;$('#memory-best').textContent=`BEST ${memoryBest} MOVES`;A.toast('すべてのペアが見つかりました ✿');}else $('#memory-status').textContent='見つけた！いい調子。';}else{memoryBusy=true;renderMemory();$('#memory-status').textContent='どこかで見た、あのかたち。';memoryTimeout=setTimeout(()=>{flipped=[];memoryBusy=false;if(gamePage==='memory')renderMemory();},800);}}}
A.actions.memoryFlip=el=>flipCard(+el.dataset.index);A.actions.memoryRestart=()=>{resetMemory();renderMemory();$('#memory-time').textContent='00:00';$('#memory-status').textContent='あせらず、ひとつずつ。';};
A.actions.gameHelp=()=>{const help=gamePage==='2048'?['2048 の遊び方','盤面を上下左右にスワイプすると、すべてのタイルが動きます。同じ数字がぶつかると合体し、数字が2倍になります。','合体した数字がスコアに加算されます。2048をつくった後も続けられます。動かせなくなったら終了です。','一手戻すは直前の1回だけ使用できます。進行状況とハイスコアは自動保存されます。']:gamePage==='snake'?['Little Snake の遊び方','スタートを押し、スワイプ・矢印キー・画面の方向ボタンでヘビを動かします。小さな実を食べると10点獲得します。','壁や自分の体にぶつかると終了です。来た方向へすぐに逆走することはできません。','アプリを離れると一時停止します。スペースキーでも一時停止できます。']:['Memory Garden の遊び方','カードを2枚めくり、同じ絵柄のペアを探しましょう。一致したカードは表向きのまま残ります。','8組のペアが揃えばクリア。2枚めくるたびに1手として数えます。少ない手数でのクリアに挑戦してください。','ハイスコアは最少手数です。アプリを開き直すと新しいお庭になります。'];A.overlay(`${A.overlayTitle(help[0])}<div class="about-copy">${help.slice(1).map(p=>`<p style="margin:22px 0">${p}</p>`).join('')}</div><button class="control-tile" data-action="closeOverlay" style="width:100%;margin-top:30px">遊んでみる</button>`);};
// Pure mechanics are exposed for regression tests; no production data hooks.
A.gameMath={mergeLine};
// Refresh badge counts now that every application has registered.
A.renderHome();
// Optional, documented deep links. All routes remain frontend-only.
const route=new URLSearchParams(location.hash.replace(/^#/,''));
if(route.get('app')&&A.apps[route.get('app')])A.open(route.get('app'),route.get('view')||undefined);
if(route.get('screen')==='lock')A.lock();
window.addEventListener('hashchange',()=>{const p=new URLSearchParams(location.hash.slice(1));if(p.get('app')&&A.apps[p.get('app')])A.open(p.get('app'),p.get('view')||undefined);else if(p.get('screen')==='lock')A.lock();else A.home();});
})();
